### ISSUE TITLE
encoding issue in one of the example?

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/bids-matlab#552]
trying to read this file: https://github.com/bids-standard/bids-examples/blob/master/fnirs_tapping/sub-01/nirs/sub-01_task-tapping_events.tsv

mangles the fieldname of the `onset` columns

```matlab
bids.util.tsvread('tests/bids-examples/fnirs_tapping/sub-01/nirs/sub-01_task-tapping_events.tsv')

ans = 
  struct with fields:

    x0xFEFFonset: [90×1 double]
        duration: [90×1 double]
      trial_type: {90×1 cell}
           value: [90×1 double]
          sample: [90×1 double]
```

@gllmflndn can you confirm you get this issue as well?

If so any clew what is happening?

**Comment by gllmflndn** [comment]
:wave: @Remi-Gau

Looks like the BOM: it was fixed in `spm_load.m` here: https://github.com/spm/spm/commit/a3889cd5d465939fdc00d38bd9a246f6be48f228

**Comment by Remi-Gau** [comment]
Sweet!!!

Thanks. I will port the fix into bids matlab.

**Comment by Remi-Gau** [comment]
@gllmflndn 

This does not fix the issue on Octave (6.4.0) where I still get this.

```matlab
fieldnames(bids.util.tsvread(tsv_file))

ans =
{
  [1,1] = x___onset
  [2,1] = duration
  [3,1] = trial_type
  [4,1] = value
  [5,1] = sample
}
```

Have not checked if spm_load is affected too.
